apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ix29k7og0-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ix29k7og0-go 
  name: ix29k7og0-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ix29k7og0-go 
